package conways.game.of.life.multiplayer;

public enum Shapes {
    BLANK, BEEHIVE, BOAT, GLIDER, HEAVYWEIGHT_SPACESHIP, LIGHTWEIGHT_SPACESHIP, LINE, LOAF, MIDDLEWEIGHT_SPACESHIP, SHIP, SQUARE, TRAFFIC_LIGHT
}
